### ISSUE TITLE
support rustls 

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#101]
rustls fixes a lot of SSL issues in many cases such as musl cross building. Is there any chance it will be added?

**Comment by Brendonovich** [comment]
Since Prisma Client Rust uses the Prisma engines internally, I don't have any control over the network layer. I know that Prisma has some options for SSL that I haven't looked into but I likely can't add anything like rustls.

**Comment by Milo123459** [comment]
I'll open an upstream issue.

**Comment by Brendonovich** [comment]
I'm sorry but it's highly unlikely this will ever happen. Changing the network stack requires core modifications to multiple dependencies and a lot of approval.

Please keep in mind that this is an _unofficial_ project. I doubt Prisma care that the engines are difficult to build on Alpine - they are only interested in bundling them for nodejs. The engines crates aren't really supposed to be used as dependencies, we're just quite fortunate that it works.
