### ISSUE TITLE
`unlink` method must receive `WhereInput` instead of `UniqueWhereInput`

### ISSUE THREAD

**Issue by teenjuna** [Brendonovich/prisma-client-rust#112]
### Discussed in https://github.com/Brendonovich/prisma-client-rust/discussions/110

<div type='discussions-op-text'>

<sup>Originally posted by **teenjuna** July 20, 2022</sup>
For example, I have an user that can be linked with many posts. In the update parameters, I can unlink it from posts by providing the ids of linked posts. In order for that to happen, I need to fetch linked posts beforehand. Is there an easier solution that doesn't involve calling the database two times?</div>

**Comment by Brendonovich** [comment]
This is actually wrong, `unlink` can accept multiple `UniqueWhereParam`s but not regular `WhereParam`s.
