### ISSUE TITLE
Enable `dependabot`

### ISSUE THREAD

**Issue by teenjuna** [Brendonovich/prisma-client-rust#113]
Hi! I just enabled GitHub's `dependabot` for my repository that uses PCR and it found several high-severity vulnerabilities in dependencies of `prisma-cli` package (e.g. dependencies of `prisma-client-rust-cli`). Maybe it's worth enabling `dependabot` for this repository, so that such alerts could be handled upstream?

**Comment by Brendonovich** [comment]
To clarify, are the vulnerabilities in the Prisma engine crates or others? If they're in the Prisma engine crates I'm not really interested in fixing them. Hardcoding dependency versions in my prisma engines fork is annoying enough, I don't want to manage different dependency versions and verify that they still work. Just don't have time. Would be great to work with the Prisma team on this but PCR is not on their list of priorities.

**Comment by teenjuna** [comment]
It's mostly low-level crates like `sized-chunks` and `crossbeam-utils`. I don't see them as direct dependencies of the PCR's CLI, so I guess it's Prisma engine crates. Closing the issue?

**Comment by Brendonovich** [comment]
Yeah will do. My philosophy is that if it's good enough for Prisma to ship to their customers then I'm comfortable including it here.
