### ISSUE TITLE
`Option` is ignored in `WhereParam`

### ISSUE THREAD

**Issue by teenjuna** [Brendonovich/prisma-client-rust#114]
Hi! I have a model with an optional number field (`Option<f64>`). I needed to query models where the field is not `None`, but turns out that `WhereParam::NumberNot` is defined as `NumberNot(f64)`, so I can't use `model::number::not(None)`. I was able to bypass that by using `model::number::gt(f64::MIN)`, but I think it would be harder for fields with non-numeric types.

**Comment by teenjuna** [comment]
Another workaround is to use this:
```rust
model::WhereParam::Not(vec![model::number::equals(None)]
```
Which is more semantically correct I guess.

**Comment by Brendonovich** [comment]
Yep, this is how you'd do that query. Note that you can use the `not!` macro to simplify it to 
```rust
not![model::number::equals(None)]
```
