### ISSUE TITLE
Change error type when accessing relations

### ISSUE THREAD

**Issue by alakhpc** [Brendonovich/prisma-client-rust#118]
Hi! I noticed when accessing a relation through the function, it returns `Result<T,  &'static str>`

Would it be better to have it return `crate::RelationNotFetchedError`? 

this would allow crates such as `anyhow` to work while, the current workaround is to map the error

```rs
    let product = server
        .product()
        .map_err(|e| anyhow::anyhow!(e))?;
```

could be written as 

```rs
    let product = server.product()?
```

maybe the error could include the field name too to get somehting like  `crate::RelationNotFetchedError(&'static str)`

**Comment by Brendonovich** [comment]
I'm open to the idea of returning a different error type, I'm just a bit puzzled as to how this would help with `anyhow`. I prefer to use `thiserror` usually. Would `RelationNotFetchedError` need to implement `anyhow::Error`?

**Comment by alakhpc** [comment]
> Would RelationNotFetchedError need to implement anyhow::Error?

no, it just needs to implement `std::error::Error`, this can be done using `thiserror` too, similar to `NewClientError` and `Error` already do it

The best way would be just to make it another variant variant in the `Error` enum.

making it like this 

```rs
#[derive(Debug, Error)]
pub enum Error {
    #[error("Error executing query: {} - {}", .0.as_known().map(|k| k.error_code.to_string()).unwrap_or("Unknown".to_string()), .0.message())]
    Execute(user_facing_errors::Error),

    #[error("Error serializing query result: {0}")]
    Serialize(#[from] serde_value::SerializerError),

    #[error("Error deserializing query result into return type: {0}")]
    Deserialize(#[from] serde_value::DeserializerError),

    // this is the new error
    #[error("Attempted to access {0} but did not fetch it using the .with() syntax")]
    RelationNotFetched(String),
}
```

**Comment by Brendonovich** [comment]
> The best way would be just to make it another variant variant in the `Error` enum.
 
 I don't think I want to do this since that enum is only for errors that occur during query execution, but I'm down to make a separate struct and implement `Error` on it. Kicking myself for not doing it sooner haha.

**Comment by alakhpc** [comment]
Yeah I'm just found out that the `Error` struct is in a different crate haha, probably should have checked that before mentioning it. 

I can try making a pr for it now if its fine

**Comment by Brendonovich** [comment]
I just implemented this on `rev = "6d379e1a7353bd5237623f4d74d09454d84541f6"`, would you mind trying it out and making sure it behaves how you'd expect?

**Comment by alakhpc** [comment]
Is `prisma-engines` supposed to be over 400mb?

**Comment by Brendonovich** [comment]
Yeeeeeah it's a big repo

**Comment by alakhpc** [comment]
Thanks!,
Yep, can confirm, works perfectly.
