### ISSUE TITLE
Why are mongodb crates installed when you're not using mongo?

### ISSUE THREAD

**Issue by Milo123459** [Brendonovich/prisma-client-rust#129]
I think it is a bit of an oversight, but there are lots of crates being downloaded that are specific to MongoDB. Maybe a feature on the crate which downloads crates only needed for that specific database to prevent this?

**Comment by Brendonovich** [comment]
This is being tracked here: https://github.com/Brendonovich/prisma-client-rust/issues/41

As for why it hasn't been done yet, the Prisma engines aren't feature gated well enough to make separating the database packages easy. I'm not happy with it and hope to at least implement `sql` and `mongodb` features at some point, but it requires a fair bit of modification of the engines that makes updating them more difficult.
