### ISSUE TITLE
Scalar list default values

### ISSUE THREAD

**Issue by Milo123459** [Brendonovich/prisma-client-rust#130]
Just a suggestion because https://github.com/prisma/prisma-engines/pull/2946 was merged and it's pretty useful and would be nice to use with this client.

**Comment by Brendonovich** [comment]
PCR 0.6.0 should use Prisma v4, I just need updated CLI binaries. I'll hit up Luca on Slack and ask for new binaries to be released.

**Comment by Brendonovich** [comment]
CLI binaries for 4.2.0 are available now, I'll update the engines to use 4.2.0 too

**Comment by Milo123459** [comment]
Thanks for bumping on the `0.6.0` branch!

**Comment by Brendonovich** [comment]
@Milo123459 Have you tried using the latest version of 0.6.0? I'm having issues compiling the engines that seems to only happen with workspaces, I'm curious whether you've encountered the same problem.

**Comment by Milo123459** [comment]
Haven't tried it yet, was going to wait until the stable release but just compiled locally and didn't encounter any issues.

**Comment by Brendonovich** [comment]
How are you using the Prisma CLI? As a separate workspace package or as an additional binary to your app?

**Comment by Milo123459** [comment]
Additional binary

**Comment by Brendonovich** [comment]
Ah ok, I'm only seeing this problem in workspace setups so that makes sense

**Comment by Milo123459** [comment]
Sorry, now that you have bumped the version on 0.6.0 are defaults on scalar lists now supported? I updated my schema and ran generate but didn't see much change in the generated client.

**Comment by Brendonovich** [comment]
I haven't added any special handling but may need to. You should at least be able to define default values for scalar lists in your schema.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/14191578/186442369-1ab92104-95a0-4036-b893-5c33bceffe42.png">

**Comment by Milo123459** [comment]
I've done that - just wanted to make sure it was actually effective.

**Comment by Brendonovich** [comment]
Looks like it does work, the client respects the default value and postgres creates the array
<img width="772" alt="image" src="https://user-images.githubusercontent.com/14191578/187174070-fad04669-f18a-47cd-80c1-46537fd4799f.png">
