### ISSUE TITLE
upsert lose data

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#132]
```
let mut create_data = vec![
    Model::first_name::set(user_input.first_name),
    Model::last_name::set(user_input.last_name),
    ...
];

let mut update_data = vec![
    Model::updated_time::set(Some(super::database_now_time())),
];
update_data.append(&mut create_data);

let user = self
    .client
    .user()
    .upsert(
        Model::id::equals(user_input.id),
        (
            Model::id::set(user_input.id),
            create_data.clone(),
        ),
        update_data.clone(),
    )
    .exec()
    .await?;
```
The code is as above, but it may cause optional data loss from time to time, the id field can be written, the rest of the fields are all default values, and user_input has data

**Comment by Brendonovich** [comment]
Can you clarify what you mean by 'data loss'? What data changes when you run that code multiple times?

**Comment by tingfeng-key** [comment]
thank you for your reply.

As in the above code, `create_data` has data, but it is not written to the database. Except for the data in the `id field`, all other data are `null` or default values.
I'll see if I can find time to provide a minimal example and reproduce the problem.

I've tried to handle this with an update (calling `upsert` again after the `upsert` completes). but nothing has changed in the data

**Comment by Brendonovich** [comment]
I'm pretty sure that's because you're calling `update_data.append`. `append` will empty `create_data` before you pass it to `upsert`, so you probably want to do `update_data.append(&mut create_data.clone)` instead.

**Comment by tingfeng-key** [comment]
I will try this approach.
But this problem doesn't happen all the time, it happens irregularly. Does this not fit well?

**Comment by Brendonovich** [comment]
If my theory is correct, here is what should happen:
First run: User is created with ID and all default fields, but not first/last names
Second run: User is found and updated with first/last names

If that's the case, then this code should work
```rust
let mut create_data = vec![
    Model::first_name::set(user_input.first_name),
    Model::last_name::set(user_input.last_name),
    ...
];

let mut update_data = vec![
    Model::updated_time::set(Some(super::database_now_time())),
];
update_data.extend(create_data.clone());

let user = self
    .client
    .user()
    .upsert(
        Model::id::equals(user_input.id),
        (
            Model::id::set(user_input.id),
            create_data,
        ),
        update_data,
    )
    .exec()
    .await?;
```

**Comment by tingfeng-key** [comment]
Thank you, that was the cause, and it's working fine now.

Can you add the `features` function, now this package is too big and it takes a lot of time to compile.

For example, I only want to use the function of `mysql`. If the packages of other databases are not included, it can reduce some compilation time.

**Comment by Brendonovich** [comment]
Glad we could get that fixed for you.

[I'd like to](https://github.com/Brendonovich/prisma-client-rust/issues/41) feature-gate database connectors, but it would require significant modifications to the Prisma engines. Maybe I'll do it one day, but I'd like it to be in collaboration with Prisma officially.
