### ISSUE TITLE
Examples don't compile, rspc missing as feature

### ISSUE THREAD

**Issue by JeremyMoeglich** [Brendonovich/prisma-client-rust#146]
When compiling the examples in this repository, I get some errors. I found that the errors can be fixed by adding `rspc` as a feature

Before (doesn't compile):
prisma-client-rust = { path = "../../" }
After (compiles):
prisma-client-rust = { path = "../../", features = ["rspc"] }

I tried this on stable and nightly
`rustc 1.63.0 (4b91a6ea7 2022-08-08)`
`rustc 1.65.0-nightly (2e35f954a 2022-09-01)`

I tried this on the basic and rocket example

```
error[E0433]: failed to resolve: could not find `rspc` in `prisma_client_rust`
   --> examples\rocket\src\db.rs:398:34
    |
398 |         :: prisma_client_rust :: rspc :: Type,
    |                                  ^^^^ could not find `rspc` in `prisma_client_rust`

error[E0433]: failed to resolve: could not find `rspc` in `prisma_client_rust`
    --> examples\rocket\src\db.rs:1353:34
     |
1353 |         :: prisma_client_rust :: rspc :: Type,
     |                                  ^^^^ could not find `rspc` in `prisma_client_rust`

error: cannot find attribute `specta` in this scope
   --> examples\rocket\src\db.rs:400:7
    |
400 |     #[specta(rename = "User", crate = "prisma_client_rust::rspc::internal::specta")]
    |       ^^^^^^

error: cannot find attribute `specta` in this scope
    --> examples\rocket\src\db.rs:1355:7
     |
1355 |     #[specta(rename = "Post", crate = "prisma_client_rust::rspc::internal::specta")]
     | 
```

**Comment by Brendonovich** [comment]
Didn't quite consider that having the rpsc feature enabled by default would do this haha. I'll make it disabled by default and add an instruction to enable it for the rspc example.
