### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#154]
I now use Postgres to store data. There is no problem printing the time data when writing locally, but after writing to the database, the time does not match.
```
local time: 2022-09-08T20:28:29.394178+08:00
database time: 2022-09-08 12:28:29.394 UTC
```
It automatically changes the time zone

**Comment by Brendonovich** [comment]
This is currently not possible, and is still an issue at https://github.com/prisma/prisma/issues/3292. Prisma stores and retrieves all times as UTC. I'd recommend converting them to the desired timezone either on your server or client.
