### ISSUE TITLE
Add to derive macro on Data

### ISSUE THREAD

**Issue by affanshahid** [Brendonovich/prisma-client-rust#166]
I am trying to integrate an axum+prisma application with [utoipa](https://github.com/juhaku/utoipa) to generate OpenAPI docs. This requires deriving `ToSchema` on the structs I want to use in the API docs.

One of my endpoints returns a prisma generated `Data` type. Can I add `#[derive(ToSchema)]` to my generated types in a way they won't get overwritten? if not what would be a good workaround other than writing the impl by hand?

**Comment by oscartbeaumont** [comment]
#100

**Comment by Brendonovich** [comment]
Adding `derive` macros to `Data` types is not possible, you'll have to implement by hand or make a custom type that derives `ToSchema` and implements `From<Data>`. Not a great experience with utiopa and other libraries, but keep an eye out for rspc's openapi plugin. Will be fully compatible with PCR and imo provide a better DX.
