### ISSUE TITLE
Features and Rustls support

### ISSUE THREAD

**Issue by 0xtlt** [Brendonovich/prisma-client-rust#172]
Good evening,
Would it be possible now or in the future to use the features in the cargo.toml file to define what we need.

And give the choice at the same time between openssl and rustls which is better?

Thanks

**Comment by Brendonovich** [comment]
If by 'define what you need` you mean the specific database connectors you need, 0.6.2 [implements this](https://prisma.brendonovich.dev/getting-started/installation#specifying-your-database)!
Openssl will be the only option going forward, rustls [has been discussed](https://github.com/Brendonovich/prisma-client-rust/issues/101) and would require so much work that it's out of scope of PCR.
