### ISSUE TITLE
Generated code for count doesn't use the where params

### ISSUE THREAD

**Issue by affanshahid** [Brendonovich/prisma-client-rust#177]
My generated code for the count method looks like:

```rust
pub fn count(self, _where: Vec<WhereParam>) -> Count<'a> {
        Count::new(
            self.client._new_query_context(),
            ::prisma_client_rust::QueryInfo::new("Candidate", _outputs()),
            vec![],
        )
}
```

Note the `_where` params isn't being passed on as the last argument, instead its just `vec![]`. This seems to be a bug unless I'm missing something.

**Comment by Brendonovich** [comment]
gonna keep this open for anyone else that encounters it before 0.6.3
