### ISSUE TITLE
Custom schema paths not respected

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#183]
Brought to my attention by @kkharji in #182.

Sorta forgot that `EngineDMMF` already provides the `schema_path` and all my logic for locating the schema is pointless, since it's way more accurate and respects custom schema paths.

**Comment by Brendonovich** [comment]
@kkharji want to try `rev = "721cf5bbce24d67970abcdacd9445edecc261f42"`? Should do the trick.

**Comment by kkharji** [comment]
Oh that was fast. I'm going to test it out tom. Thanks @Brendonovich

**Comment by Brendonovich** [comment]
@kkharji Are you able to test this sometime?

**Comment by kkharji** [comment]
Hey @Brendonovich, my apologies, I switched to the setup recommended. But it does work. Thanks
