### ISSUE TITLE
@db.Date directive is recognised as DateTime with Postgres

### ISSUE THREAD

**Issue by westernwontons** [Brendonovich/prisma-client-rust#185]
My Prisma Schema has the following table:
```
model Food {
  id        Int      @id @default(autoincrement())
  food_type String   @db.VarChar(20)
  name      String   @db.VarChar(200)
  price     Float    @db.Real
  amount    Float    @db.Real
  total     Float    @db.Real
  date      DateTime @db.Date
}
```

Even though I set `@db.Date`, it's still recognised as DateTime when I want to use Prisma. Am I missing something or this is intended?

Here is a screenshot of the generated type signature:

<img width="988" alt="Screenshot 2022-10-23 at 22 46 47" src="https://user-images.githubusercontent.com/75550932/197414687-4033776d-7a6a-4b0a-9cc9-19d099620103.png">

**Comment by Brendonovich** [comment]
Looks like Prisma Client JS uses the same type for `Date` as `DateTime`:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/14191578/197417414-d0c401b0-733e-4c6f-863e-3e6e5dc20dd5.png">

Though using Chrono's `Date<Tz>` would probably be a good candidate for #83. Can't promise it'll happen soon but I'll keep it in mind.

**Comment by westernwontons** [comment]
Would you be accepting PR's for this?

**Comment by Brendonovich** [comment]
Yes, but it would be for 0.7.0 instead of 0.6.3. I'd want to implement many native types instead of just this one, so I'm going to close this issue in favour of #83.
