### ISSUE TITLE
Use `r#` to avoid name clashes

### ISSUE THREAD

**Issue by codemaster138** [Brendonovich/prisma-client-rust#194]
Reading the documentation for `prisma-client-rust`, I came across this section about [Naming Clashes](https://prisma.brendonovich.dev/getting-started/setup#naming-clashes).

This is not an immediate problem for me since my current schema creates no naming clashes, but it does make me wonder – shouldn't it be relatively easy to use [Raw Identifiers](https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html), the _idiomatic_ way to avoid naming clashes, whenever a field has the same name as a reserved keyword?

For example, a field named `type` would show up as `r#type` in the generated code, etc.

**Comment by Brendonovich** [comment]
Yeah, raw identifiers are possible. I just don't like how they look so decided against it. That may have been the wrong decision though, and with PCR being more than just a personal project now I should probably change it. There's always the option to rename fields and models that use raw identifiers, I guess.

**Comment by Brendonovich** [comment]
@codemaster138 Does `rev = "acce0c893d6b48ce90a6141460d5712d4a24c4cc"` implement this for you? Should be good to go.

**Comment by codemaster138** [comment]
@Brendonovich As I said before, I don't actually need this in my project, but I made a simple schema with `type` as a field name. It does seem to be escaped, but fsr the enum namespace bug is back on this rev...

**Comment by Brendonovich** [comment]
@codemaster138 Dw about that, I probs need to rebase the branch. As long as the escaping works then it's fine.
