### ISSUE TITLE
Use relative path to `MIGRATIONS_DIR` instead of absolute?

### ISSUE THREAD

**Issue by alakhpc** [Brendonovich/prisma-client-rust#195]
I'm trying to use the migrations, which inserts 
```rs
pub static MIGRATIONS_DIR: &::prisma_client_rust::migrations::include_dir::Dir = &::prisma_client_rust::migrations::include_dir::include_dir!(
    "/Users/name/Projects/nwb2/migrations"
);
```
into the generated file. This however fails when you try and run it on another machine (or in docker).
Would it be better to store a relative path instead?

**Comment by alakhpc** [comment]
same for `DATAMODEL_STR` actually

**Comment by Brendonovich** [comment]
`include_dir` only allows resolving paths relative to `$CARGO_MANIFEST_DIR`, so a looot more work that I don't want to do would have to be done to calculate the relative path. Besides, the client isn't designed to be shared across machines and should be regenerated wherever it is needed (it shouldn't even be checked into git), so the absolute path changing should be allowed.

**Comment by HuakunShen** [comment]
I have the same problem.

I use the `prisma.rs` in `lib.rs` 

```rs
pub mod prisma;
```

If I don't include the `prisma.rs` in git, then `cargo prisma generate` will fail.
