### ISSUE TITLE
Prisma enum generation broken

### ISSUE THREAD

**Issue by styxpilled** [Brendonovich/prisma-client-rust#197]
When using a prisma enum, the generated rust code includes an E0412 error.
Prisma enum example:
```prisma
model Thing {
  id   Int       @id
  kind ThingKind
}

enum ThingKind {
  Foo
  Bar
  Creature
}
```
The generated rust enum in `_prisma > read_filters` gives a `cannot find type ThingKind in this scope
not found in this scope rustc(E0412)` error.
```rs
pub enum ThingKindFilter {
    InVec(Vec<ThingKind>),
    NotInVec(Vec<ThingKind>),
    Not(ThingKind),
}
```
Adding `use crate::prisma::ObjectKind;` above the rust enum, per the compiler suggestion, fixes the issue.

**Comment by Brendonovich** [comment]
@styxpilled @codemaster138 can you try using `rev = "a0fb19d25d6869c6398a338e5228d80c81a8c354"` and see if it fixes the problem? It's not a complete nice fix but it should get the job done for now.

**Comment by codemaster138** [comment]
@Brendonovich yeah, that seems to have fixed the issue. Thanks for handling this so quickly!
