### ISSUE TITLE
Failure to correctly qualify enums in generated code

### ISSUE THREAD

**Issue by codemaster138** [Brendonovich/prisma-client-rust#199]
#### Problem Description
When using enums, the generated `prisma.rs` file references the enums only with their name rather than a fully qualified identifier, leading to errors such as:

```
error[E0412]: cannot find type `MyEnum` in this scope
   --> src/prisma.rs:XXX:XX
    |
XXX |       Not(MyEnum),
    |           ^^^^^^^ not found in this scope
    |
help: consider importing this enum
    |
XXX |     use crate::prisma::MyEnum;
    |
```

#### To Reproduce
1. Clone [codemaster138/prisma-client-rust-repro](https://github.com/codemaster138/prisma-client-rust-repro)
2. Run `cargo prisma generate`
3. Run `cargo check`

#### Expected Behavior
The code generator should either:
- Emit `use crate::prisma::<Enum Name>` statements as needed or
- Use fully qualified specifiers for enums (e.g. `Not(crate::prisma::MyEnum)` instead of `Not(MyEnum)`

#### Environment
- Rust Version: 1.63.0
- Operating System: macOS Monterey (12.6)
- Processor: Apple M1 (aarch64)
- Prisma Client Rust Version: 0.6.3

#### Additional Context
This seems like an issue that should almost definitely have been caught by now, so, if you can't reproduce this, the possibility of being an M1 platform bug should be investigated...

**Comment by Brendonovich** [comment]
Similar to #197. Will get on these ASAP for 1.6.4.

**Comment by codemaster138** [comment]
Oops, hadn't seen that issue. Sorry!

**Comment by Brendonovich** [comment]
No worries, this problem is a bit different so it's ok. Really appreciate the detailed issue haha.

**Comment by codemaster138** [comment]
@Brendonovich I'm not sure whether this is a clean fix, but for the example I provided, changing [`read_filters.rs`:17](https://github.com/Brendonovich/prisma-client-rust/blob/e12e6932be7d224410784b52143384cc9235da3b/cli/src/generator/read_filters.rs#L17) like this:

```diff
-                quote!(#variant_name(#typ)),
+                quote!(#variant_name(super::super::#typ)),
```

might help...?

**Comment by Brendonovich** [comment]
@codemaster138 I think that will break primitive types (which is what I made the read filter change for). I'll need to check whether the type is a builtin or custom type.

**Comment by Brendonovich** [comment]
On second look, this is actually a duplicate. Am working on it rn.
