### ISSUE TITLE
which type should be used when apply include in find

### ISSUE THREAD

**Issue by swaitw** [Brendonovich/prisma-client-rust#201]
```rust
use crate::{prisma::{PrismaClient, user::{Data as User, self}}};
pub async fn find_user_by_email(client:&PrismaClient, email: String) -> Option<User> {
    let user = client.user().find_unique(user::email::equals(email)).include(user::include!({
	profile
    })).exec().await.unwrap();
    user
}
```

here  will show unmatched type. so does anyone know how to fix it? thanks.

**Comment by Brendonovich** [comment]
Looks like you've misspelled `profile` as `profille`. Would that be what's causing the problem?

**Comment by swaitw** [comment]
sorry, the spelling is right in my code, but show error like that:
 user
     |     ^^^^ expected struct `prisma::user::Data`, found struct `find_user_by_email_and_password::{closure#0}::Data`
     |

**Comment by Brendonovich** [comment]
Ah, you'll want to check out [this section](https://prisma.brendonovich.dev/reading-data/select-include#using-types-outside-queries) of the docs for using `include` types as function return types.

**Comment by swaitw** [comment]
sorry, thanks for your answer but a little bit confused here, do i need create these type manulaly ? if not, where can i find them.

**Comment by Brendonovich** [comment]
You'll want to do something like this:
```rust
use crate::{prisma::{PrismaClient, user::{Data as User, self}}};

user::include!(user_with_profile { profile });

pub async fn find_user_by_email(client: &PrismaClient, email: String) -> user_with_profile::Data {
  let user = client
    .user()
    .find_unique(user::email::equals(email))
    .include(user_with_profile::include())
    .exec()
    .await
    .unwrap()
}
```

**Comment by swaitw** [comment]
> 

works for me, you save my life, thanks a lot for that.
