### ISSUE TITLE
create a record with relation  in link table

### ISSUE THREAD

**Issue by swaitw** [Brendonovich/prisma-client-rust#202]
Hi,
i got tree tabls like this:
user table：
| id | email|
|---|------|

user role table:
| id | name|
|---|------|

user to user role table:
| user_id | role_id|
|---|------|

so is there a way i can link the user to the user role at the same time when create a new user.
thanks

**Comment by Brendonovich** [comment]
Doing that would require creating a nested record, which Prisma supports but PCR does not yet. That is being tracked in #44
