### ISSUE TITLE
Warn user if CLI version and runtime version don't match

### ISSUE THREAD

**Issue by oscartbeaumont** [Brendonovich/prisma-client-rust#23]
The code generated by the CLI may rely on stuff exported from the `prisma-client-rust` library which is added to the individual projects which use this library. A compiler error should be thrown if the code generated by the CLI expected a higher version of the `prisma-client-rust` dependency in the specific project, to prompt the developer to update it.

**Comment by Brendonovich** [comment]
#35 will make this a non-issue
