### ISSUE TITLE
Traits for making extensible queries

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#232]
Traits like `Where`, `Order` etc for making wrapper functions that apply preset settings.

**Comment by tingfeng-key** [comment]
Can `Query Traits` be used outside the library? Or an example of using `Query Traits`

**Comment by Brendonovich** [comment]
Not currently, though that's a kinda similar idea to the `partial_unchecked!` macro. I've got a couple of ideas but I'm not quite sure.
