### ISSUE TITLE
Big problem...

### ISSUE THREAD

**Issue by GQAdonis** [Brendonovich/prisma-client-rust#242]
It seems you may have a really big problem here with this implementation, because some of the types you depend on are now private in `prisma-engines`, which mean a complete rewrite.  I tried to mitigate some by at least testing to see if making private versions of the engines project may work by making things public in my build, but there were too many issues.

Do you have a plan for this?

**Comment by Brendonovich** [comment]
Can you elaborate? The 0.6.4 branch uses v4.8.0 of the engines and it's fine, if I need access to any private structs I just make them public.
Keep in mind that this project doesn't use `prisma/prisma-engines`, but instead my fork `Brendonovich/prisma-engines`, which is how I'm able to offer feature flagging for database connectors.
