### ISSUE TITLE
Scalar Lists missing read filters

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#257]
Initially reported by @Alivers.
Should be fixed on `1f6474396363bab8c4cdd70c342055779b36909d`.

**Comment by Dennis-Zhang-SH** [comment]
Hi, any progress on this issue?

**Comment by Dennis-Zhang-SH** [comment]
sorry, change the rev works just fine.

**Comment by arnm** [comment]
Im a rust newbie, is that a commit hash I can specify in the `Cargo.toml`? When will this go into a proper tag?

**Comment by Brendonovich** [comment]
> Im a rust newbie, is that a commit hash I can specify in the `Cargo.toml`? When will this go into a proper tag?

Yep, use `rev = "1f6474396363bab8c4cdd70c342055779b36909d"` instead of `tag = "0.6.4"`. I should have a new release out today.
