### ISSUE TITLE
Feature Request: Upgrade Prisma CLI to at least v4.10

### ISSUE THREAD

**Issue by ChristianIvicevic** [Brendonovich/prisma-client-rust#263]
Unfortunately GitHub isn't really happy about me having a customized fork so I can't fork the repo again to contribute a PR myself. However I'd be happy if you can upgrade the CLI to v4.10 which enables the new `--generator` flag to selectively generate files which is useful to separate jobs in CIs in mixed monorepo codebases.

**Comment by Brendonovich** [comment]
I do plan on doing this and even started work on it in my forks, I just didn't want to do it with 0.6.5. I'll make sure the next update has it though.

**Comment by jareducherek** [comment]
@Brendonovich could you point to how multiple generators are used? there does not seem to be an option such as `prisma generate --generator client1` that the npm version of prisma has. 

Currently I have resorted to commenting out the second generator when I need to run `cargo prisma generate`.

**Comment by Brendonovich** [comment]
@jareducherek use `main` instead of 0.6, 0.7 isn't out yet
