### ISSUE TITLE
Prisma Rust Client Generation

### ISSUE THREAD

**Issue by NelminDev** [Brendonovich/prisma-client-rust#264]
Hey mates, I did setup the Prisma Rust Client like the [docs](https://prisma.brendonovich.dev/getting-started/installation) says but when I execute `cargo prisma generate` the file `prisma.rs` doesn't get created. I dont get a error in the CLI

**Comment by Brendonovich** [comment]
Guessing you got it figured out? 😆

**Comment by NelminDev** [comment]
Yes, I created in my crate instead of a workspace crate
