### ISSUE TITLE
CLI incompatible with rust version < 1.58

### ISSUE THREAD

**Issue by PierreV23** [Brendonovich/prisma-client-rust#27]
Compiling serde v1.0.136
   Compiling mysql_common v0.28.2
   Compiling futures-executor v0.3.21
   Compiling tokio-util v0.6.9
   Compiling tokio-util v0.7.1
   Compiling tokio-native-tls v0.3.0 (https://github.com/pimeys/tls?branch=vendored-openssl#6d0e6fc7)
   Compiling asynchronous-codec v0.5.0
   Compiling async-native-tls v0.4.0
   Compiling mobc v0.7.3 (https://github.com/prisma/mobc?tag=1.0.0#75c68f10)
   Compiling trust-dns-proto v0.20.4
   Compiling tokio-rustls v0.22.0
   Compiling schema-ast v0.1.0 (https://github.com/Brendonovich/prisma-engines?rev=8c1da2fdc058b7af8905a61491856cade06f952f#8c1da2fd)
error: there is no argument named `name`
  --> C:\Users\xxx\.cargo\git\checkouts\prisma-engines-8e1416dd0e571d11\8c1da2f\libs\datamodel\schema-ast\src\parser\parse_composite_type.rs:78:49
   |
78 | ...                   "Defining `@{name}` attribute for a field in a composite type is not allowed."
   |                                   ^^^^^^

   Compiling futures v0.3.21
   Compiling opentelemetry v0.16.0
error: could not compile `schema-ast` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Brendonovich** [comment]
Huh, this is really strange. Can you please provide the rust version and operating system you are using? I've been able to compile the `schema-ast` crate just fine.

**Comment by PierreV23** [comment]
> Huh, this is really strange. Can you please provide the rust version and operating system you are using? I've been able to compile the `schema-ast` crate just fine. Update: Looks like that line is using the Rust 1.58.0+ ability to capture variables in format strings from the enclosing scope: https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html. I'm guessing you're using an older version of Rust that doesn't have this feature yet.

Oh yeah my bad sorry,  I thought I was on a pretty recent version of rust. I think I confused my pc's version with the version on my laptop...

Btw, where am I supposed to run `prisma-client-rust generate` on Windows10?

**Comment by Brendonovich** [comment]
Huh, that's strange. Copied that schema into the example folder and ran it with CLI v0.3.1 and it generated just fine. Maybe it's a Windows thing since this has only been tested on Mac and Linux?

**Comment by PierreV23** [comment]
> Huh, that's strange. Copied that schema into the example folder and ran it with CLI v0.3.1 and it generated just fine. Maybe it's a Windows thing since this has only been tested on Mac and Linux?

Ahh its sad to hear its only for Linux and Mac, any way to still get it working?

I tried WSL but it didn't work :(

**Comment by Brendonovich** [comment]
I'll try get it tested on windows and let you know. In the meantime, I'll close this issue since the problem was resolved.
