### ISSUE TITLE
bug - changing primary key names

### ISSUE THREAD

**Issue by brecht-derooms** [Brendonovich/prisma-client-rust#271]
Coming from a db that is not managed by prisma but by another ORM I noticed that it generates a.
- drop constraint
- rename constraint
- new constraint.

I assume this is a minor bug and that the rename constraint shouldn't have been generated in this case or that the add constraint should have not bene generated but in that case the SQL syntax is not entirely correct either (it might require to "alter table" statements iirc).

```
-- AlterTable
ALTER TABLE "product_reservations" DROP CONSTRAINT "pk-product_reservations",
RENAME CONSTRAINT "pk-product_reservations" TO "product_reservations_pkey",
... column changes
ADD CONSTRAINT "product_reservations_pkey" PRIMARY KEY ("id");
```

Easy to fix manually though.

**Comment by Brendonovich** [comment]
PCR doesn't manage migration SQL, you'll want to report this over in the [Prisma repo](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml).
