### ISSUE TITLE
`use of undeclared crate or module 'prisma'` after updating to current version

### ISSUE THREAD

**Issue by bangbaew** [Brendonovich/prisma-client-rust#298]
![image](https://user-images.githubusercontent.com/29559559/227918831-58b9cf11-5394-417d-b262-1906e83d4371.png)
This is the update information after running `cargo update`, and it causes the app to break, tried rerunning `prisma generate` multiple times, didn't fix the problem, my version before this update worked fine.
![image](https://user-images.githubusercontent.com/29559559/227919296-3e04f7d0-7ee2-4ead-a154-96d1de001bdb.png)
![image](https://user-images.githubusercontent.com/29559559/227919339-05b81d74-05e3-4f67-91a8-bd7cdb7ba788.png)

**Comment by bangbaew** [comment]
![image](https://user-images.githubusercontent.com/29559559/227981379-c125b916-f170-4734-9244-6ce30b39925e.png)
This error also happens on all versions when i use select.

**Comment by Brendonovich** [comment]
The first error is interesting as I don't remember changing anything about enum path resolution, but the second one is likely related to this: https://prisma.brendonovich.dev/reading-data/select-include#setup.

**Comment by bangbaew** [comment]
> The first error is interesting as I don't remember changing anything about enum path resolution, but the second one is likely related to this: https://prisma.brendonovich.dev/reading-data/select-include#setup.
> 
> Oh wait are you using `branch = "main"`? `df1d2ac1` is an unreleased commit.

Sorry for not reading carefully, the second one is fixed now, thanks!
And yes, I was using main branch in this issue, I thought it was the released one.
