### ISSUE TITLE
panicked at: called `Result::unwrap()` on an `Err` value: Error("invalid type: null")

### ISSUE THREAD

**Issue by fernandomarca** [Brendonovich/prisma-client-rust#30]
Hello, after a while I realized that queries can return NULL when a record is not found. 
I think it was what is described here. "Error handling: Queries do not return Result types, but will in a future version."
I'm looking at the struct Query impl to see how serde_json could handle this behind the scenes.
Was there any progress on this?
thanks.

**Comment by Brendonovich** [comment]
Yeah, this will be implemented in the next release. Try using the master branch directly (for the library and CLI) and you should find it works.
