### ISSUE TITLE
Struct PrismaClient: derive Clone

### ISSUE THREAD

**Issue by OnlyCS** [Brendonovich/prisma-client-rust#304]
It doesn't conflict with any properties...

**Comment by Brendonovich** [comment]
The problem with this is that the performance of `PrismaClient::clone` would be worse and more unpredictable than `Arc<PrismaClient>::clone`. In future I may add more internals to the client with more stuff that needs cloning. Cloning a single `Arc` in user-space is cheaper and more reliable, so I'm going to keep recommending that approach.
