### ISSUE TITLE
partial_unchecked Fields should be public

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#311]
When it is called in other libraries in my workspace, the field cannot be assigned a value because it is private

**Comment by tingfeng-key** [comment]
When I assign values to the generated code externally, it is still a private field

**Comment by tingfeng-key** [comment]
I will place the code generated by PCR in one service's scratch in the workspace, and then use it in another scratch called cli, but it will still prompt for field liberalization

**Comment by Brendonovich** [comment]
Try `cargo update -p prisma-client-rust`, should fix it

**Comment by tingfeng-key** [comment]
Okay, thank you. I don't quite understand why I changed the tag version number in Cargo.toml to 0.6.8 and it doesn't take effect, and I have executed cargo clean
