### ISSUE TITLE
partial_unchecked extend

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#334]
For example, I have a `CreateParams` as follows:
```rust
system_user::partial_unchecked!(CreateParams {
    nickname
    role_id
    dept_id
    phone
    email
    sex
    password
    salt
    describe
    expire_time
    status
});
```
Then I need to add a username field when updating, so I need to copy `CreateParams`. Is it possible to expand on the basis of `CreateParams`, such as this:
```rust
system_user::partial_unchecked_extend!(CreateParams,UpdateParams {
    username
});
```
UpdateParams is now as follows:
```rust
system_user::partial_unchecked!(UpdateParams {
    username
    nickname
    role_id
    dept_id
    phone
    email
    sex
    password
    salt
    describe
    expire_time
    status
});

```

**Comment by Brendonovich** [comment]
This is _probably_ possible by making `partial_unchecked` emit its own `macro_rules` that can construct `CreateParams` from `UpdateParams`, but I feel like it's just not worth it compared to how much effort it would take. Besides, I don't think`CreateParams` and `UpdateParams` will be interchangeable in 0.7.0 anyway.

**Comment by tingfeng-key** [comment]
ok, that would be really cool if it came to fruition one day

**Comment by Brendonovich** [comment]
`CreateParams` and `UpdateParams` definitely aren't going to be compatible with each other in future, plus doing this would be wayyy to much overhead for me to maintain.

**Comment by tingfeng-key** [comment]
Understood, thank you for your reply. I will close it
