### ISSUE TITLE
Does it support postgresql index with some feature?

### ISSUE THREAD

**Issue by athxx** [Brendonovich/prisma-client-rust#348]
I have tables with some columns base on `point` type, and need to create `gist()` index, and turn on buffering. 

the SQL is : 
```sql
create index IdxGeoUser on GeoStore using gist(pt) with (buffering=on);
```
but there seems no way to create `with (buffering=on)` this attribute
```prisma
model GeoUser {
    uid BigInt               @id @default(autoincrement())
    pt  Unsupported("point")

    @@index([pt], type: Gist) // ??? how to add `with (buffering=on)`
}
```

Is there any way can solve this problem?

**Comment by Brendonovich** [comment]
If [Prisma's docs](https://www.prisma.io/docs/concepts/components/prisma-schema/indexes) don't say it's possible then I'd assume it's not doable
