### ISSUE TITLE
[bug] Error: (query-engine binary) on MacOS M1 

### ISSUE THREAD

**Issue by ejazahm3d** [Brendonovich/prisma-client-rust#359]
When I try to run any prisma command, it throws this error on MacOS M1. I have tried the same code on linux, and it generated the client successfully. 

```sh
❯ cargo prisma generate
   Compiling prisma-cli v0.1.0 (/Users/ejazahmed/Desktop/Developer/rust/rust-sea/prisma-cli)
    Finished dev [unoptimized + debuginfo] target(s) in 2.10s
warning: the following packages contain code that will be rejected by a future version of Rust: bigint v4.4.3, connection-string v0.1.13
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/debug/prisma-cli generate`
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: (query-engine binary)
Details:
[Context: getDmmf]

Prisma CLI Version : 4.8.0
```

**Comment by Brendonovich** [comment]
Sounds like a Rosetta problem, try running this first:
```
softwareupdate --install-rosetta --agree-to-license
```

**Comment by ejazahm3d** [comment]
@Brendonovich Thanks. That worked. :) 
I will close this.

**Comment by mjm918** [comment]
> Sounds like a Rosetta problem, try running this first:
> 
> ```
> softwareupdate --install-rosetta --agree-to-license
> ```

<img width="1377" alt="Screenshot 2023-07-12 at 9 36 34 AM" src="https://github.com/Brendonovich/prisma-client-rust/assets/17846525/fdc3ef6e-90e0-4862-9949-5db4666e1cd9">


The solution isn't working for me. Any hints you can suggest ?
