### ISSUE TITLE
[MySQL] cannot find function `create_record` in module `write`

### ISSUE THREAD

**Issue by xlxAciDxlx** [Brendonovich/prisma-client-rust#370]
PCR Version: Anything > 0.6.8

I'm trying to upgrade PCR and RSPC, but I'm running into the following error. Not sure if there's any other information I could provide that'd be helpful, but feel free to let me know if there is!

```
    Compiling sql-query-connector v0.1.0 (https://github.com/Brendonovich/prisma-engines?branch=new-4.14.0-pcr#45b026c8)
error[E0425]: cannot find function `create_record` in module `write`
  --> C:\Users\user\.cargo\git\checkouts\prisma-engines-8e1416dd0e571d11\45b026c\query-engine\connectors\sql-query-connector\src\database\operations\write.rs:97:25
   |
97 |     let insert = write::create_record(model, args, ctx);
   |                         ^^^^^^^^^^^^^ not found in `write`
```

**Comment by Brendonovich** [comment]
Hmmm I can't guarantee any stability for anything > 0.6.8 but I may have to look into this for the next release.

**Comment by xlxAciDxlx** [comment]
I can switch back to SQLite so I can still test stuff, so it's not a huge deal. Just wanted to report it since it would be nice to use MySQL for enums and such haha

**Comment by xlxAciDxlx** [comment]
Can confirm this is fixed :D Thanks a lot!
