### ISSUE TITLE
M2 Mac Query engine error, contect getDmmf

### ISSUE THREAD

**Issue by Autumn-Ou** [Brendonovich/prisma-client-rust#375]
Unable to use any prisma cli commands outside of prisma init, all others result in the following error.
## Error
```
Prisma schema loaded from prisma/schema.prisma
Error: (query-engine binary)
Details: 
[Context: getDmmf]

Prisma CLI Version : 4.8.0
```
## Rust Toolchain
```
Default host: aarch64-apple-darwin
rustup home:  /Users/autumn/.rustup

stable-aarch64-apple-darwin (default)
rustc 1.71.1 (eb26296b5 2023-08-03)
```
## System
```
CPU: Apple M2
Memory: 8GB
```

This occurs in both projects using prisma-rust but also using the prisma-client-rust repo testing example projects

I currently do not know what the cause is and the error message has not lead anywhere.

**Comment by Brendonovich** [comment]
Does running this help?
`softwareupdate --install-rosetta --agree-to-license`

**Comment by Brendonovich** [comment]
Yeah I'll add a note in the docs about it
