### ISSUE TITLE
Investigate only bundling required database connectors

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#41]
Would probably involve modifying prisma-engines

**Comment by John0x** [comment]
Is there a workaround for this right now?
Takes ages to download from within docker

**Comment by Brendonovich** [comment]
@John0x Not currently, I have to modify prisma-engines to do so and just don't have time to do it right now. You could try utilising docker layer caching and building primsa-client-rust separately to your other dependencies with `cargo build -p prisma-client-rust`.

**Comment by Brendonovich** [comment]
Gonna put this on hold again, I just don't have time atm

**Comment by oscartbeaumont** [comment]
I just opened PR prisma/prisma-engines#3157 about separating the `sql` and `monogdb` features. I will be interested if they merge it because the Prisma Engines already had a convention to feature gate `sql` vs `monogodb` but it just wasn't done properly everywhere.

**Comment by Brendonovich** [comment]
This now works on the `feature-gate-dbs` branch. Will be doing testing to see if it's suitable for release.

**Comment by Brendonovich** [comment]
72dbb636473d3b93ede4fc99361b4cb8533dd72b
