### ISSUE TITLE
PrismaClient set log level

### ISSUE THREAD

**Issue by jareducherek** [Brendonovich/prisma-client-rust#428]
I spent ~20 mins scanning the documentation and code, but could not figure out how to pass any parameters to PrismaClient::build in order to set the log level.

I want to remove INFO from the log level for my client as it is spamming my logs.

https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging

**Comment by Brendonovich** [comment]
I assume you're using the `tracing` ecosystem for your logs, in which case PCR doesn't have any logs of its own, but the dependency `quaint` does, and it logs all the SQL that it executes as INFO.
You'll need to setup a filter yourself with something like [`EnvFilter`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html).

**Comment by jareducherek** [comment]
@Brendonovich Thanks for the pointer. This is working. Ultimately I am using ```EnvFilter::new(format!("crate_name=info,other=warn"))``` to filter out the queries from the PrismaClient.
