### ISSUE TITLE
Build for Docker

### ISSUE THREAD

**Issue by lutfi-haslab** [Brendonovich/prisma-client-rust#431]
Sorry i am new in rust world. 
Do you have example for the deployment, because it is not found in the documentation?

**Comment by lutfi-haslab** [comment]
Hello, i can confirm i successfully deploy rust with prisma-client-rust. 
i also deployed the app in fly.io https://rust-with-prisma.fly.dev/user

here are my Dockerfile

```
# Build stage
FROM rust:1.70.0-slim-bullseye AS build

ARG APP_NAME="with-prisma"

RUN apt-get update -y && \
  apt-get install -y pkg-config make g++ libssl-dev && \
  rustup target add x86_64-unknown-linux-gnu

WORKDIR /build

COPY . .

RUN cargo prisma generate
# /root/.cache/prisma/binaries/cli/4.8.0/prisma-cli-linux-x64

RUN cargo build --release --target x86_64-unknown-linux-gnu

CMD ["/build/target/x86_64-unknown-linux-gnu/release/with-prisma"]
```

however the image build is really big, here is the detail:
<img width="359" alt="image" src="https://github.com/Brendonovich/prisma-client-rust/assets/108409669/0ccd256c-d5b9-4ece-abe5-8ddde422c1c9">

i am looking the way, for decreasing the image size. Do you have any suggestion?

**Comment by Brendonovich** [comment]
Use a multi-stage build and only copy over the executable in the second stage, everything else in `target` is unnecessary.
