### ISSUE TITLE
How to generate output that split into many small files?

### ISSUE THREAD

**Issue by kittomfv** [Brendonovich/prisma-client-rust#459]
Currently, the output of `cargo prisma generate` create  only a file that setup at

```
generator client {
  provider = "cargo prisma"
  output   = "../src/db.rs"
}
```
I am wondering how to split into many files because the size of the output is too big and difficult to index when loading in vscode or jetbrain. 
Any suggestions for that?

**Comment by oscartbeaumont** [comment]
You can use the  `client_format` option to configure this.

This was implemented in #368 (another related issue #397). As far as I am aware it has not been released so you may need to import PCR from the `main` branch.

To use it in your `schema.prisma` you can do something similar to:
```prisma
generator client {
  provider      = "cargo prisma"
  output        = "../../crates/prisma/src/prisma"
  client_format = "folder" // < This bit here
}
```
