### ISSUE TITLE
Crate.io package Yanked

### ISSUE THREAD

**Issue by Minniesse** [Brendonovich/prisma-client-rust#460]
Hi I would like to inform that the package is yanked, is there any problem to the website?
Link:
https://crates.io/crates/prisma-client-rust
https://crates.io/crates/prisma-client-rust-cli

We tried to cargo.lock already with --locked but we still got a problem
``` bash
Downloading https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-4.8.0-linux-x64.gz to /home/moonie/.cache/prisma/binaries/cli/4.8.0/prisma-cli-linux-x64"
```
at this part, it also cannot download the tar.xz file

It would be nice if this could be fixed :)

**Comment by Brendonovich** [comment]
As discussed on Discord, crates.io distribution is no longer supported
