### ISSUE TITLE
Improve explicit many-to-many

### ISSUE THREAD

**Issue by John0x** [Brendonovich/prisma-client-rust#59]
It would be nice if you could use explicit m2m relations the same way as implicit ones.
Currently you have to provide extra information for explicit relations, but I think you could probably infer that stuff from the prisma schema?

**Comment by Brendonovich** [comment]
What do you mean by 'have to provide extra information'? I'm genuinely confused 😅

**Comment by John0x** [comment]
# Example
## Schema
```prisma
model Program {
  id           Int      @id @default(autoincrement()) 
  grantor GrantorOnPrograms[]
}

model Grantor {
  name     String              @id
  programs GrantorOnPrograms[]
}

model GrantorOnPrograms {
  id          Int     @id @default(autoincrement())
  program     Program @relation(fields: [programId], references: [id])
  programId   Int
  grantor     Grantor @relation(fields: [grantorName], references: [name])
  grantorName String
} 
```

## Insert
You can't just do:
```rust
  db.program()
      .create(
          program::id::set(123),
          vec![program::grantor::link(vec![
              grantor::name::equals("whatever"),
          ])],
      )
      .exec()
      .await?;
```

**Comment by John0x** [comment]
> The problem with doing so is that the client isn't aware of what a join table is and I don't plan for it to ever be. That is not a feature Prisma Client JS has, and it kind of defeats the purpose of an explicit join table in the first place, since they are supposed to yield control of the join table from Prisma to you.
> 
> If you want nested creates, which would allow the Program and GrantorOnPrograms records to be created in the same query, I have planned it in #44 but probably won't implement it for a while.
> 
> Also, if you have a join table like the example you provided, it's probably worth just using an implicit one. Not sure of your exact use case though.

Ah, okay. Understandable. I thought that the js client would allow the join tables to be automated. 
Yep, I would have preferred implicit joins, but we have some unfortunate restrictions on the db schema 😬
