### ISSUE TITLE
Enums incorrectly treated as GraphQL types

### ISSUE THREAD

**Issue by auser** [Brendonovich/prisma-client-rust#61]
I'm getting a bug when running `generate`:

```bash
{"jsonrpc":"2.0","id":1,"result":{"manifest":{"defaultOutput":"prisma.rs","denylist":null,"prettyName":"Prisma Client Rust","requiresEngines":null,"requiresGenerators":null}}}
thread 'main' panicked at 'Unsupported type: Role', /Users/user/.cargo/git/checkouts/prisma-client-rust-fa967aa5ad0ec391/72326a9/cli/src/generator/types.rs:128:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My schema is pretty simple and yet I can't get around this. 

```prisma
// ...
model User {
  id   String @id @default(cuid())
  role UserRole
}

enum UserRole {
  ADMIN
  USER
}
```

What did I miss? Is this a bug? What am I doing wrong?

**Comment by auser** [comment]
Some more investigation reveals that it comes from this line:

https://github.com/Brendonovich/prisma-client-rust/blob/main/cli/src/generator/types.rs#L128

What would be the right way add support for custom enums?

**Comment by Brendonovich** [comment]
From looking at your error message I'm not quite sure, but it shouldn't be too hard to fix. I'm currently working on some other changes first, but I'll get this done in the next release

**Comment by auser** [comment]
@Brendonovich it looks like it's iterating through types in the generator and if it doesn't find the type, it throws the error. 

How might we be able to iterate through the custom enum types? And any ETA on the next release?

**Comment by Brendonovich** [comment]
Custom enum types are exposed in Prisma's DMMF that the rest of the client is built off. I implemented enums earlier but looks like I messed it up at some point. I'm aiming to get 0.5.0 out by the end of the week.
