### ISSUE TITLE
Null value not handled for EnvValues

### ISSUE THREAD

**Issue by auser** [Brendonovich/prisma-client-rust#66]
With a `prisma/schema.prisma` file present with a datasource that uses `env()` from prisma, the generator fails to generate a `prisma.rs`:

```prisma
datasource db {
  provider = "postgresql"
  url           = env("DATABASE_URL")
}
```

Error:

```bash
thread 'main' panicked at 'datasources[0].url.value: invalid type: null, expected a string at line 1 column 1136', $HOME/.cargo/git/checkouts/prisma-client-rust-fa967aa5ad0ec391/97d469e/cli/src/lib.rs:109:25
```

This is on the latest main branch.

The error occurs when `serde_json` tries to deserialize the input from the `schema.prisma` file.

**Comment by Brendonovich** [comment]
Looks like I didn't have the proper types for env values, should be fixed by cb78ad08b653ed74d427d5e923f82771813a1a58.
