### ISSUE TITLE
Empty UniqueWhereParam enum

### ISSUE THREAD

**Issue by geovie** [Brendonovich/prisma-client-rust#69]
Hi, first of all thanks for this crate!

When updating to the latest commit (https://github.com/Brendonovich/prisma-client-rust/commit/31a864ae09e835ff046469345bf6e413ae54a30f) I found that the generated `UniqueWhereParam` had no variants anymore...

model to reproduce:
```prisma
model Post {
  userId    String
  projectId String
  content   String
  @@id([userId, projectId, content])
}
```

With commit https://github.com/Brendonovich/prisma-client-rust/commit/94bef1de5dd94ec144bc41fd85f3c24a58cc034f the generated `UniqueWhereParam` enum looks like this:
```rust
    pub enum UniqueWhereParam {
        UserIdProjectIdContentEquals(String, String, String),
    }
```
after that commit an empty enum is generated:
```rust
    pub enum UniqueWhereParam {}
```

Best regards

**Comment by Brendonovich** [comment]
Ah yep, Prisma treats primary key fields separately to regular fields. Thanks for letting me know!

**Comment by Brendonovich** [comment]
Should be fixed, try using `rev = "b6d1bd901f1d475cba8184e6cddae980510d3b39"` instead of `tag = "0.5.0"`

**Comment by geovie** [comment]
Works 👍 thanks a lot

**Comment by Brendonovich** [comment]
Sweet, I'll include it in 0.5.1 in a few days
