### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#76]
Why is this crate not on crates.io yet? Seems logical it should be there

**Comment by Brendonovich** [comment]
Prisma Client Rust depends on [prisma-engines](https://github.com/prisma/prisma-engines), which are only available via GitHub and so publishing on crates is not possible. Previously this wasn't the case, but the accuracy and time saved by pulling in the Prisma engines directly is enough of a reason to warrant GitHub-only publishing.
