### ISSUE TITLE
Embedded/Composite types

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#82]
## `create`
- [x] `set`

## `update`
- [x] `set`
- [x] `unset`
- [x] `update`
- [x] `upsert`
- [x] `push`
- [x] `updateMany`
- [x] `deleteMany`

## Filters
- [x] `is`
- [x] `equals`
- [x] `isNot`
- [x] `isSet`
- [x] `isEmpty`
- [x] `every`
- [x] `some`
- [x] `none`

<br/>

- [x] `order`

**Comment by Congyuwang** [comment]
Any update on this! Currently, using `type` in `schema.prisma` gives `unimplemented!()` panic.

**Comment by Brendonovich** [comment]
Nah I haven't been putting any work into it. MongoDB isn't a priority or even something I know much about

**Comment by Alivers** [comment]
Thanks for your work to offer prisma rust tools. Is there any update on this? For the mongodb, the composite types is truely needed to store nested document.

**Comment by Brendonovich** [comment]
No update sadly, but if I find time I may implement them for the next update. They should work similar to regular models if I understand correctly.

**Comment by Congyuwang** [comment]
Tried to implement it, but don't really know how to implement the generator part, then give up, lol.

**Comment by Brendonovich** [comment]
Aight this should be doable
<img width="687" alt="image" src="https://user-images.githubusercontent.com/14191578/227689919-e022aaf5-78ce-4015-b4ae-754dec1f27a8.png">

**Comment by Brendonovich** [comment]
Docs: https://prisma-client-rust-git-main-brendonovich.vercel.app/extra/composite-types
