### ISSUE TITLE
Generation broken following docs

### ISSUE THREAD

**Issue by tbillington** [Brendonovich/prisma-client-rust#90]
I'm following along the steps in the docs, and I'm up to here https://github.com/Brendonovich/prisma-client-rust/blob/main/docs/02-setup.md.

The docs don't say which command to run to get your generated client, so I ran `cargo prisma generate`. I got some validation errors related to the `schema.prisma`. My schema file is exactly as displayed in the above link. I'm using the workspace setup so my prisma command alias is this `prisma = "run -p prisma-cli --bin prisma-cli --"`.

Thank you!

```
> cargo prisma generate
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target/debug/prisma-cli generate`
Prisma schema loaded from schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:7
   | 
 6 | generator client {
 7 |     provider      = "cargo prisma" // Corresponds to the cargo alias created earlier
 8 |     output        = "./src/prisma.rs" // The location to generate the schema. Is relative to the position of the schema
   | 
error: Error validating: This line is not a valid definition within a generator.
  -->  schema.prisma:8
   | 
 7 |     provider      = "cargo prisma" // Corresponds to the cargo alias created earlier
 8 |     output        = "./src/prisma.rs" // The location to generate the schema. Is relative to the position of the schema
 9 | }
   | 

Validation Error Count: 2
```

On version specified by the docs
`prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }`

**Comment by tbillington** [comment]
Okay this was _super_ weird, the comment at the end of the lines was causing the issue... After removing the line comments on 7 and 8 it was fine 🙃

**Comment by Brendonovich** [comment]
Oh whoops, turns out that comments aren't allowed inside generator blocks... will need to change that!
