### ISSUE TITLE
Derive `Clone` for generated `PrismaClient` 

### ISSUE THREAD

**Issue by devtomio** [Brendonovich/prisma-client-rust#97]
I'm trying to attach the generated `PrismaClient` to use with [`axum`](https://github.com/tokio-rs/axum)'s extension api. Putting `#[derive(Clone)]` on the generated struct gives this error.

Error:
```rs
the trait bound `dyn prisma_client_rust::query_core::QueryExecutor + std::marker::Send + std::marker::Sync: std::clone::Clone` is not satisfied
required because of the requirements on the impl of `std::clone::Clone` for `std::boxed::Box<dyn prisma_client_rust::query_core::QueryExecutor + std::marker::Send + std::marker::Sync>`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
```

**Comment by Brendonovich** [comment]
Yes, this is intended behaviour. The client uses connection pooling internally and should only exist once in your application.
